### ISSUE TITLE
Implementar página de registro

### ISSUE THREAD

**Issue by Bielframos** [Bielframos/zerei#2]
## Tasks
- [ ] Inicializar página
- [ ] Adicionar formulário de registro
- [ ] Checkbox para termos e condições
- [ ] Implementar prevenção de spam (reCAPTCHA)
- [ ] Tratamento de erros (Erro no registro, Usuário já cadastrado)
