### ISSUE TITLE
Implementar página de recuperação de senha

### ISSUE THREAD

**Issue by Bielframos** [Bielframos/zerei#3]
## Tasks
- [ ] Formulário de recuperação de senha
- [ ] Implementar notificação de envio de e-mail para recuperar senha
- [ ] Implementar lógica de recuperação alinhada ao Appwrite
