### ISSUE TITLE
Implementar página adminstrativa

### ISSUE THREAD

**Issue by Bielframos** [Bielframos/zerei#4]
## Tasks
- [ ] Implementar visualização de jogos registrados
- [ ] Implementar recurso para adição de novos jogos
- [ ] Implementar recursos de filtros e busca
- [ ] Implementar botão para edição/remoção do jogo
